<script setup lang="ts">
import { ref, computed, watch } from 'vue';

const props = defineProps({
  from: {
    type: Number,
    default: 0,
  },
  to: {
    type: Number,
    default: 0,
  },
});

const styleStr = ref('translateY(0em)')

const numbers = computed(() => {
  return generateNumberList(props.from, props.to)
})

// const style = computed(() => {
//   return { transform: 'translateY(' + (-numbers.value.length) + 'em' }
// })

watch(() => props.to, (newCount, oldCount) => {
  setTimeout(() => {
    styleStr.value = 'translateY(0em)'


    let num = generateNumberList(props.from, props.to)
    setTimeout(() => {
      styleStr.value = 'translateY(' + (-num.length) + 'em'
    }, 10)
  }, 10)

}, {
  immediate: true
})

function generateNumberList(a: number, b: number) {
  let result: number[] = [];

  if (a < b) {
    for (let i = a + 1; i < b; i++) {
      result.push(i);
    }
  } else if (a > b) {
    for (let i = a + 1; i < b + 10; i++) {
      result.push(i % 10);
    }
  }

  return result;
}
</script>

<template>
  <div class="number-limit">
    <div
      class="number-box"
      :style="{ transform: styleStr }"
    >
      <div
        v-for="(item) in numbers"
        :key="item"
      >{{ item }}</div>
      <div>{{ to }}</div>
    </div>
  </div>
</template>

<style scoped>
.number-limit {
  height: 1em;
  line-height: 1em;
  overflow: hidden;
  position: relative;
  transition: transform 0.5s ease-out;
}

.number-box {
  display: flex;
  flex-direction: column;
  transition: transform 0.5s ease-out;

}

/* ----------------------------------------------
 * Generated by Animista on 2024-2-5 17:15:38
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-bottom
 * ----------------------------------------
 */
@keyframes slide-in-blurred-bottom {
  0% {
    transform: translateY(100px) scaleY(2.5) scaleX(0.2);
    transform-origin: 50% 100%;
    filter: blur(40px);
    opacity: 0;
  }

  100% {
    transform: translateY(0) scaleY(1) scaleX(1);
    transform-origin: 50% 50%;
    filter: blur(0);
    opacity: 1;
  }
}
</style>
